Repository Mil0w0/diabetiC, pull requests merged in 2023-02, with the labels that each got.

#2 Login menu
  .gitignore
  README.md
  database/database.c
  database/database.h
  docs/technical_documentation.md
  entries/entry.c
  entries/entry.h
  glycemia/glycemia.c
  glycemia/glycemia.h
  main.c
  users/users.c
  users/users.h
Labels: DO NOT MERGE YET

#5 Checking glycemia
  database/database.c
  database/database.h
  entries/entry.c
  entries/entry.h
  glycemia/glycemia.c
  main.c
  users/users.c
Labels: DO NOT MERGE YET

#10 Alert glycemia messages
  glycemia/glycemia.c
  glycemia/glycemia.h
Labels: enhancement

#16 Fixing argument type warning on GCC
  entries/entry.c
Labels: warning

#14 More documentations
  docs/installing
  docs/installing_sqlite.md
  docs/technical_documentation.md
Labels: documentation
